platform :ios, '9.0'

target 'Affilio' do
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    # 'BatchedBridge', # Required For React Native 0.45.0+
    'Core',
    # Add any other subspecs you want to use in your project
  ]

  # Required by RNFirebase
  pod 'Firebase/Core'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/iOS'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  # pod 'Firebase/AdMob'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  # For Crashlytics:
  # pod 'Fabric', '~> 1.7.2'
  # pod 'Crashlytics', '~> 3.9.3'

  # pod 'Firebase/Crash'
  # pod 'Firebase/Database'
  # pod 'Firebase/DynamicLinks'
  # pod 'Firebase/Messaging'
  # pod 'Firebase/RemoteConfig'
  pod 'Firebase/Storage'

  # pod 'GoogleMaps'

  # pod 'RNBackgroundGeolocation', :path => '../node_modules/react-native-background-geolocation'

  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'

  # pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  # pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

  pod 'GoogleSignIn', '~> 4.4.0'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'FBSDKCoreKit', '~>4.42.0'
  pod 'FBSDKLoginKit', '~>4.42.0'
  pod 'FBSDKShareKit', '~>4.42.0'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'RNShare', :path => '../node_modules/react-native-share'

end

post_install do |installer|
	 ## Fix for XCode 12.5
	find_and_replace("../node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm",
	"_initializeModules:(NSArray<id<RCTBridgeModule>> *)modules", "_initializeModules:(NSArray<Class> *)modules")
	find_and_replace("../node_modules/react-native/ReactCommon/turbomodule/core/platform/ios/RCTTurboModuleManager.mm",
			"RCTBridgeModuleNameForClass(module))", "RCTBridgeModuleNameForClass(Class(module)))")
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end

def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)
      if text != replace
          puts "Fix: " + name
          File.open(name, "w") { |file| file.puts replace }
          STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end
